services:
  web:
    container_name: fluently_dev_server
    build:
      context: .
      target: build
    working_dir: /rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/rails
      - bundle_data:/usr/local/bundle
    ports:
      - "3001:3000"
    environment:
      RAILS_ENV: development
      BUNDLE_WITHOUT: ""
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: fluently_dev
      DB_USERNAME: fluently_dev
      DB_PASSWORD: fluently_dev
      TEST_DB_NAME: fluently_test
    depends_on:
      - db

  db:
    container_name: fluently_dev_db
    image: postgres:16
    environment:
      POSTGRES_DB: fluently_dev
      POSTGRES_USER: fluently_dev
      POSTGRES_PASSWORD: fluently_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

volumes:
  postgres_data:
  bundle_data:
